import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';

async function seed(page: Page, count = 3) {
  await page.goto('');
  return page.evaluate(async count => {
    const dbPath = '/library/src/data/database.ts', draftPath = '/library/src/data/shelfDraft.ts';
    const { db } = await import(dbPath), { createDraft } = await import(draftPath), draft = await createDraft(db, null);
    const canvas = document.createElement('canvas'); canvas.width = 900; canvas.height = 600; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#ff0000'; ctx.fillRect(0,0,450,600); ctx.fillStyle = '#0000ff'; ctx.fillRect(450,0,450,600);
    const bytes = Uint8Array.from(atob(canvas.toDataURL('image/jpeg',0.9).split(',')[1]), char => char.charCodeAt(0)), blob = new Blob([bytes],{type:'image/jpeg'});
    const hash = [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');
    for(let i=0;i<Math.ceil(count/25);i++){const imageId=crypto.randomUUID(); await db.images.add({id:imageId,blob,mimeType:'image/jpeg',width:900,height:600,byteLength:blob.size,sha256:hash,sourceUrl:null,createdAt:new Date().toISOString()});draft.images.push({id:crypto.randomUUID(),name:'synthetic-'+i+'.jpg',inputHash:hash,storedImageId:imageId,preparedHash:hash,status:'recognized',message:null});}
    for(let i=0;i<count;i++){const title='ספר מדף '+i;draft.items.push({id:crypto.randomUUID(),imageId:draft.images[Math.floor(i/25)].id,item:{title,authors:[],isbn:null,danacode:null,publisher:null,visibleText:title,evidenceByField:{title:[title],authors:[],isbn:[],danacode:[],publisher:[]},imageIndex:0,bbox:[0,0,0.5,1],uncertaintyReasons:['מחבר אינו נראה']},model:'gemini-3.8-flash',fetchedAt:new Date().toISOString(),status:'detected',selectedFields:[],bookId:null,copyId:null});}
    draft.status='complete';await db.recognitionDrafts.put(draft);return{id:draft.id,itemIds:draft.items.map((item:{id:string})=>item.id)};
  },count);
}
async function open(page: Page,id:string){await page.getByRole('button',{name:'צילום מדף בכמה תמונות',exact:true}).click();await page.getByRole('combobox',{name:'בחירת טיוטת מדף',exact:true}).selectOption(id);}
async function review(page: Page,index:number){await page.getByText(new RegExp('^סקירת פריט '+index+' ·')).click();}
async function applyAndApprove(page: Page,index:number){const scope=page.locator('details').filter({has:page.getByRole('button',{name:'עדכון טיוטת פריט '+index,exact:true})});await page.getByRole('button',{name:'עדכון טיוטת פריט '+index,exact:true}).click();await expect(scope.getByText('ערכי הפריט נשמרו בטיוטה. דרוש אישור נפרד.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'אישור פריט '+index,exact:true}).click();await expect(scope.getByText('הפריט אושר. הוא יתווסף רק בשמירת המאושרים.',{exact:true})).toBeVisible();}
async function counts(page:Page){return page.evaluate(async()=>{const path='/library/src/data/database.ts';const{db}=await import(path);return{books:await db.books.count(),copies:await db.copies.count(),sources:await db.metadataSources.count()};});}
test('T18 review is explicit, local crop never uploads, cancel keeps books empty and approved save survives reload/backup',async({page})=>{
  const requests:string[]=[],errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.route('https://generativelanguage.googleapis.com/**',route=>{requests.push(route.request().url());return route.abort();});
  const seeded=await seed(page);await open(page,seeded.id);await page.getByRole('button',{name:'בדיקת אזור הספר בפריט 1',exact:true}).click();const crop=page.getByRole('img',{name:'אזור הספר בתמונת המדף',exact:true});await expect.poll(()=>crop.evaluate(img=>(img as HTMLImageElement).naturalWidth)).toBe(450);await expect.poll(()=>crop.evaluate(img=>(img as HTMLImageElement).naturalHeight)).toBe(600);
  await review(page,1);await expect(page.getByLabel('שם מהתמונה לפריט 1: ספר מדף 0',{exact:true})).not.toBeChecked();await expect(page.getByLabel('שם הספר לפריט 1',{exact:true})).toHaveValue('');await page.getByLabel('שם מהתמונה לפריט 1: ספר מדף 0',{exact:true}).check();await page.getByLabel('שם הספר לפריט 1',{exact:true}).fill('שם שערכתי');await page.getByRole('combobox',{name:'מה לשמור לפריט 1',exact:true}).selectOption('new');
  await page.keyboard.press('Escape');await expect(page.getByText('יש שינויים שלא נשמרו. לסגור ולוותר עליהם?',{exact:true})).toBeVisible();await page.getByRole('button',{name:'חזרה לעריכה',exact:true}).click();await expect(page.getByLabel('שם הספר לפריט 1',{exact:true})).toHaveValue('שם שערכתי');
  await applyAndApprove(page,1);expect((await counts(page)).books).toBe(0);await page.getByRole('button',{name:'סיכום לפני שמירת מאושרים',exact:true}).click();await expect(page.getByText('1 ספרים חדשים · 0 עותקים נוספים · 2 פריטים לא יישמרו בפעולה זו',{exact:true})).toBeVisible();await page.getByRole('button',{name:'ביטול השמירה',exact:true}).click();expect((await counts(page)).books).toBe(0);await page.getByRole('button',{name:'סיכום לפני שמירת מאושרים',exact:true}).click();await page.getByLabel('בדקתי את הסיכום ואני מאשר שמירה לספרייה',{exact:true}).check();await page.getByRole('button',{name:'שמור מאושרים',exact:true}).click();await expect(page.getByText('1 פריטים מאושרים נשמרו בספרייה.',{exact:true})).toBeVisible();expect(await counts(page)).toEqual({books:1,copies:1,sources:1});
  await page.keyboard.press('Escape');await page.getByRole('link',{name:'הגדרות',exact:true}).click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'הורדת גיבוי הספרייה',exact:true}).click();const backup=JSON.parse((await readFile((await(await downloading).path())!)).toString());expect(backup.formatVersion).toBe(8);expect(backup.tables.recognitionDrafts[0].items[0]).toMatchObject({id:seeded.itemIds[0],status:'saved'});expect(backup.tables.metadataSources[0].userOverriddenFields).toEqual(['title']);
  await page.reload();await page.getByRole('link',{name:'כל הספרים',exact:true}).click();await open(page,seeded.id);await expect(page.getByText('הפריט נשמר בספרייה. חידוש או שמירה חוזרת אינם מוסיפים אותו שוב.',{exact:true})).toBeVisible();expect(await counts(page)).toEqual({books:1,copies:1,sources:1});expect(requests).toEqual([]);expect(errors).toEqual([]);
});
test('T09 real competing windows save extra copies once and preserve existing bibliographic values',async({page,context})=>{
  const seeded=await seed(page,2),book=await page.evaluate(async()=>{const booksPath='/library/src/data/books.ts',dbPath='/library/src/data/database.ts';const{db}=await import(dbPath),{saveBook,emptyInput}=await import(booksPath);return saveBook(db,{...emptyInput,title:'ספר קיים',personalNotes:'הערה קיימת'});});await open(page,seeded.id);
  for(let i=1;i<=2;i++){await review(page,i);await page.getByRole('combobox',{name:'מה לשמור לפריט '+i,exact:true}).selectOption('copy');await page.getByRole('combobox',{name:'ספר היעד לפריט '+i,exact:true}).selectOption(book.id);await applyAndApprove(page,i);}
  await page.getByRole('button',{name:'סיכום לפני שמירת מאושרים',exact:true}).click();await expect(page.getByText('0 ספרים חדשים · 2 עותקים נוספים · 0 פריטים לא יישמרו בפעולה זו',{exact:true})).toBeVisible();await page.getByLabel('בדקתי את הסיכום ואני מאשר שמירה לספרייה',{exact:true}).check();
  const preview=await page.evaluate(async id=>{const dbPath='/library/src/data/database.ts',reviewPath='/library/src/data/shelfReview.ts';const{db}=await import(dbPath),{previewApproved}=await import(reviewPath);return previewApproved(db,id);},seeded.id),peer=await context.newPage();await peer.goto('');
  const results=await Promise.all([page,peer].map(window=>window.evaluate(async preview=>{const dbPath='/library/src/data/database.ts',reviewPath='/library/src/data/shelfReview.ts';const{db}=await import(dbPath),{saveApproved}=await import(reviewPath);return saveApproved(db,preview);},preview)));expect(results.reduce((n,result)=>n+result.saved,0)).toBe(2);expect(await counts(page)).toEqual({books:1,copies:3,sources:2});
  const after=await page.evaluate(async id=>{const path='/library/src/data/database.ts';const{db}=await import(path);return db.books.get(id);},book.id);expect(after.title).toBe('ספר קיים');expect(after.personalNotes).toBe('הערה קיימת');await peer.close();
});
test('T18 fifty-item list edits an item in the middle, applies selected catalog field and remains usable at 360px',async({page})=>{
  await page.route('https://openlibrary.org/**',async route=>{const path=new URL(route.request().url()).pathname;await route.fulfill({json:path==='/search.json'?{docs:[{key:'/works/OL88W',title:'יצירה',editions:{docs:[{key:'/books/OL88M',title:'ספר קטלוג סינתטי'}]}}]}:path==='/books/OL88M.json'?{title:'ספר קטלוג סינתטי',publishers:['הוצאה סינתטית'],publish_date:'2014'}:{name:'מחבר'}});});
  const seeded=await seed(page,50);await open(page,seeded.id);await review(page,25);await page.getByLabel('שם מהתמונה לפריט 25: ספר מדף 24',{exact:true}).check();const article=page.locator('article.notice').filter({has:page.getByRole('button',{name:'בדיקת אזור הספר בפריט 25',exact:true})});await article.getByText('חיפוש והשלמה מקטלוגים',{exact:true}).click();await article.getByRole('button',{name:'חיפוש בקטלוגים',exact:true}).click();await article.getByRole('button',{name:'בחירת מועמד ספר קטלוג סינתטי',exact:true}).click();await article.locator('.catalog-choice').filter({hasText:'הוצאה לאור:'}).getByRole('checkbox').check();await article.getByRole('button',{name:'החלת השדות שנבחרו',exact:true}).click();await expect(page.getByLabel('הוצאה לאור לפריט 25',{exact:true})).toHaveValue('הוצאה סינתטית');await page.getByLabel('הערות אישיות לפריט 25',{exact:true}).fill('עריכה באמצע הרשימה');await page.getByRole('combobox',{name:'מה לשמור לפריט 25',exact:true}).selectOption('new');await applyAndApprove(page,25);
  await page.setViewportSize({width:360,height:800});await page.getByRole('button',{name:'סיכום לפני שמירת מאושרים',exact:true}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/phase12-360-review.png',fullPage:true});await page.getByRole('button',{name:'סיכום לפני שמירת מאושרים',exact:true}).click();await page.getByLabel('בדקתי את הסיכום ואני מאשר שמירה לספרייה',{exact:true}).check();await page.getByRole('button',{name:'שמור מאושרים',exact:true}).click();await expect(page.getByText('1 פריטים מאושרים נשמרו בספרייה.',{exact:true})).toBeVisible();expect(await counts(page)).toEqual({books:1,copies:1,sources:2});
  const saved=await page.evaluate(async()=>{const path='/library/src/data/database.ts';const{db}=await import(path);return(await db.recognitionDrafts.toArray())[0].items.filter((row:{status:string})=>row.status==='saved').map((row:{id:string})=>row.id);});expect(saved).toEqual([seeded.itemIds[24]]);
});
