import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const canary = 'DUMMY_browser_memory_key_canary_0987654321';
const item = { title: 'ספר תמונה סינתטי', authors: [], isbn: '9780140328721', danacode: '002001', publisher: null, visibleText: 'ספר תמונה סינתטי\n9780140328721\n002001', evidenceByField: { title: ['ספר תמונה סינתטי'], authors: [], isbn: ['9780140328721'], danacode: ['002001'], publisher: [] }, imageIndex: 0, bbox: [0, 0, 1, 1], uncertaintyReasons: ['מחבר אינו נראה בתמונה.'] };
const payload = { candidates: [{ finishReason: 'STOP', content: { parts: [{ text: JSON.stringify({ items: [item] }) }] } }] };
async function openVision(page: Page) {
  await page.goto(''); await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click(); await page.getByLabel('שם הספר', { exact: true }).fill('שם ידני'); await page.getByLabel('שם מחבר 1', { exact: true }).fill('מחבר ידני'); await page.getByRole('button', { name: 'זיהוי ספר מתמונה', exact: true }).click(); await expect(page.getByRole('heading', { name: 'זיהוי ספר מתמונה', exact: true })).toBeVisible();
}
async function prepare(page: Page) {
  const data = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 900; canvas.height = 1200; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#f6efe0'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = '#163b4f'; ctx.font = '48px sans-serif'; ctx.fillText('ספר תמונה סינתטי', 80, 300); return canvas.toDataURL('image/png').split(',')[1]; });
  await page.getByLabel('בחירת תמונת ספר', { exact: true }).setInputFiles({ name: 'synthetic-book.png', mimeType: 'image/png', buffer: Buffer.from(data, 'base64') }); await expect(page.getByRole('img', { name: 'תמונת הספר לפני חיתוך', exact: true })).toBeVisible(); await expect(page.getByText('בדוק כיוון וחיתוך, ואז הכן את התמונה לפני שליחה.', { exact: true })).toBeVisible(); const preparing = page.getByRole('button', { name: 'הכנת התמונה לזיהוי', exact: true }); await preparing.scrollIntoViewIfNeeded(); await preparing.click(); await expect(page.getByRole('img', { name: 'תמונה מוכנה לשליחה לזיהוי', exact: true })).toBeVisible();
}
async function configure(page: Page) { await page.getByLabel('מפתח Gemini אישי', { exact: true }).fill(canary); await page.getByLabel('בדקתי שהפרויקט של המפתח הוא Free, ללא חיוב פעיל', { exact: true }).check(); await page.getByLabel('אני מסכים לשליחת התמונה המוכנה ל־Google Gemini', { exact: true }).check(); await page.getByRole('button', { name: 'הגדרת המפתח לזיכרון בלבד', exact: true }).click(); }

test('T17/T24 explicit image selection, manual overrides and source evidence survive save/reload/backup without the key', async ({ page }) => {
  const requests: string[] = [], errors: string[] = []; page.on('console', message => { if (message.text().includes(canary)) errors.push(message.text()); }); page.on('pageerror', error => errors.push(error.message));
  await page.route('https://generativelanguage.googleapis.com/**', async route => { requests.push(route.request().url()); expect(route.request().headers()['x-goog-api-key']).toBe(canary); expect(route.request().postData()).not.toContain(canary); await route.fulfill({ json: payload }); });
  await openVision(page); await prepare(page); await expect(page.getByRole('button', { name: 'שליחת התמונה לזיהוי', exact: true })).toBeDisabled(); expect(requests).toEqual([]); await configure(page);
  await page.getByRole('button', { name: 'שליחת התמונה לזיהוי', exact: true }).click(); await expect(page.getByRole('heading', { name: 'בחירת שדות מהתמונה', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'החלת השדות מהתמונה על הטיוטה' })).toBeDisabled(); await expect(page.getByText('מחבר אינו נראה בתמונה.', { exact: true })).toBeVisible(); await expect(page.locator('.catalog-choice')).toHaveCount(3);
  await page.locator('.catalog-choice').filter({ hasText: 'שם הספר:' }).getByRole('checkbox').check(); await page.locator('.catalog-choice').filter({ hasText: 'דאנאקוד:' }).getByRole('checkbox').check(); await page.getByRole('button', { name: 'החלת השדות מהתמונה על הטיוטה', exact: true }).click(); await expect(page.getByLabel('שם הספר', { exact: true })).toHaveValue('ספר תמונה סינתטי'); await expect(page.getByLabel('שם מחבר 1', { exact: true })).toHaveValue('מחבר ידני');
  const storedBeforeSave = await page.evaluate(async () => { const path = '/library/src/data/database.ts'; return (await import(/* @vite-ignore */ path)).db.books.count(); }); expect(storedBeforeSave).toBe(0); await page.getByLabel('שם הספר', { exact: true }).fill('תמונה עם עריכה ידנית'); await page.getByRole('button', { name: 'שמירת הספר', exact: true }).click();
  const privateScan = await page.evaluate(async () => { const path = '/library/src/data/database.ts', { db } = await import(/* @vite-ignore */ path); const tables = await Promise.all(db.tables.map((table: { toArray: () => Promise<unknown[]> }) => table.toArray())); return JSON.stringify({ tables, local: { ...localStorage }, session: { ...sessionStorage } }); }); expect(privateScan).not.toContain(canary);
  await page.reload(); await page.getByRole('button', { name: /תמונה עם עריכה ידנית.*1 עותקים/ }).click(); await page.getByText('מקורות המידע (1)', { exact: true }).click(); await expect(page.getByRole('heading', { name: 'זיהוי מתמונה · Gemini', exact: true })).toBeVisible(); await expect(page.getByText('נערך ידנית: שם הספר', { exact: true })).toBeVisible(); await page.getByText('ראיות הזיהוי מהתמונה', { exact: true }).click(); await expect(page.getByText('gemini-3.8-flash · single-book-v1', { exact: true })).toBeVisible(); await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'הגדרות', exact: true }).click(); await expect(page.getByLabel('מפתח Gemini אישי', { exact: true })).toHaveValue(''); const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'הורדת גיבוי הספרייה', exact: true }).click(); const bytes = await readFile((await (await download).path())!); const backup = JSON.parse(bytes.toString()); expect(bytes.toString()).not.toContain(canary); expect(backup.tables.metadataSources[0].recognition.item.visibleText).toBe(item.visibleText); expect(backup.tables.books[0].isbn13).toBeNull(); expect(backup.tables.books[0].danacode).toBe('002001'); expect(requests).toHaveLength(1); expect(errors).toEqual([]);
});
test('T17 closing during a pending request ignores the late response and preserves the book draft', async ({ page }) => {
  let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve; }); let calls = 0;
  await page.route('https://generativelanguage.googleapis.com/**', async route => { calls++; await gate; await route.fulfill({ json: payload }).catch(() => {}); });
  await openVision(page); await prepare(page); await configure(page); await page.getByRole('button', { name: 'שליחת התמונה לזיהוי', exact: true }).click(); await expect.poll(() => calls).toBe(1); await page.keyboard.press('Escape'); release(); await expect(page.getByLabel('שם הספר', { exact: true })).toHaveValue('שם ידני'); await expect(page.getByRole('heading', { name: 'בחירת שדות מהתמונה', exact: true })).toHaveCount(0); await page.getByRole('button', { name: 'זיהוי ספר מתמונה', exact: true }).click(); await expect(page.getByRole('heading', { name: 'בחירת שדות מהתמונה', exact: true })).toHaveCount(0); await expect(page.getByRole('button', { name: 'שליחת התמונה לזיהוי', exact: true })).toHaveCount(0);
});
test('T17 quota stops without retry or payment, local image changes invalidate prepared results at 360px', async ({ page }) => {
  let calls = 0; await page.route('https://generativelanguage.googleapis.com/**', async route => { calls++; await route.fulfill({ status: 429, json: { error: canary } }); });
  await openVision(page); await prepare(page); await configure(page); await page.getByRole('button', { name: 'שליחת התמונה לזיהוי', exact: true }).click(); await expect(page.getByText('המכסה או מגבלת הקצב הושגה. הזיהוי נעצר ללא ניסיון נוסף או רכישת קרדיטים.', { exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'שליחת התמונה לזיהוי', exact: true })).toBeDisabled(); expect(calls).toBe(1); await page.getByRole('button', { name: 'מחיקת המפתח מהזיכרון', exact: true }).click(); await expect(page.getByText('המפתח נמחק מהזיכרון.', { exact: true })).toBeVisible(); expect(calls).toBe(1); await page.getByRole('combobox', { name: 'סיבוב התמונה', exact: true }).selectOption('90'); await expect(page.getByRole('img', { name: 'תמונה מוכנה לשליחה לזיהוי', exact: true })).toHaveCount(0); await page.setViewportSize({ width: 360, height: 800 }); await page.getByRole('button', { name: 'הכנת התמונה לזיהוי', exact: true }).scrollIntoViewIfNeeded(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: 'test-results/phase10-360-crop.png', fullPage: true });
});
