import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const key = 'DUMMY_shelf_memory_key_0123456789012345';
const book = (title = 'ספר מדף סינתטי') => ({ title, authors: [], isbn: null, danacode: '002001', publisher: null, visibleText: title + ' 002001', evidenceByField: { title: [title], authors: [], isbn: [], danacode: ['002001'], publisher: [] }, imageIndex: 0, bbox: [0,0,0.4,1], uncertaintyReasons: ['מחבר לא נראה בתמונה'] });
const payload = (titles = ['ספר מדף סינתטי']) => ({ candidates: [{ finishReason: 'STOP', content: { parts: [{ text: JSON.stringify({ items: titles.map(title => book(title)) }) }] } }] });
async function open(page: Page) { await page.goto(''); await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click(); await page.getByRole('button', { name: 'צילום מדף בכמה תמונות', exact: true }).click(); await expect(page.getByRole('heading', { name: 'צילום מדף בכמה תמונות', exact: true })).toBeVisible(); }
async function configure(page: Page) { if (await page.getByText('מפתח אישי מוגדר בדפדפן הזה.', { exact: true }).isVisible()) return; await page.getByLabel('מפתח Gemini אישי', { exact: true }).fill(key); await page.getByLabel('בדקתי שהפרויקט של המפתח הוא Free, ללא חיוב פעיל', { exact: true }).check(); await page.getByLabel('אני מסכים לשליחת התמונה המוכנה ל־Google Gemini', { exact: true }).check(); await page.getByRole('button', { name: 'שמירת מפתח Gemini', exact: true }).click(); }
async function fixture(page: Page) {
  const base64 = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 900; canvas.height = 600; const ctx = canvas.getContext('2d')!; ctx.fillStyle = '#eee'; ctx.fillRect(0,0,900,600); ctx.fillStyle = '#173b4f'; ctx.font = '42px sans-serif'; ctx.fillText('ספר מדף סינתטי', 40,200); return canvas.toDataURL('image/png').split(',')[1]; });
  return { name: 'synthetic-shelf.png', mimeType: 'image/png', buffer: Buffer.from(base64, 'base64') };
}
async function newDraft(page: Page, keep: boolean, count = 2) {
  await page.getByRole('button', { name: 'פתיחת טיוטת מדף חדשה', exact: true }).click();
  if (keep) await page.getByLabel('שמירת תמונה מוכנה במכשיר לצורך התהליך והגיבוי', { exact: true }).check();
  const image = await fixture(page); await page.getByLabel('הוספת תמונות מדף', { exact: true }).setInputFiles(Array.from({ length: count }, (_, i) => ({ ...image, name: 'synthetic-' + i + '.png' })));
  await expect(page.getByText('התמונות נוספו לתור. שליחה מתחילה רק בלחיצה מפורשת.', { exact: true })).toBeVisible();
}
async function chooseDraft(page: Page) { const select = page.getByRole('combobox', { name: 'בחירת טיוטת מדף', exact: true }); const id = await select.locator('option').nth(1).getAttribute('value'); await select.selectOption(id!); }
test('T18 multiple files serial extraction, overlap remains separate, retained source and backup survive reload without a key', async ({ page }) => {
  let calls = 0; const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); page.on('console', message => { if (message.text().includes(key)) errors.push('canary leaked'); });
  await page.route('https://generativelanguage.googleapis.com/**', async route => { calls++; expect(route.request().headers()['x-goog-api-key']).toBe(key); expect(route.request().postData()).not.toContain(key); expect(JSON.parse(route.request().postData()!).generationConfig.responseJsonSchema.properties.items.maxItems).toBe(40); await route.fulfill({ json: payload(['ספר מדף סינתטי', 'ספר מדף כרך ב']) }); });
  await open(page); await newDraft(page, true); expect(calls).toBe(0); await expect(page.getByRole('button', { name: 'התחלת או חידוש התור', exact: true })).toBeDisabled(); await configure(page); await page.getByRole('button', { name: 'התחלת או חידוש התור', exact: true }).click();
  await expect(page.getByText('2 תמונות · 4 פריטים בטיוטה', { exact: true })).toBeVisible(); expect(calls).toBe(2); await expect(page.getByText('מזהה זהה; ייתכן עוד עותק או חפיפה. הפריט נשאר נפרד.', { exact: true })).toHaveCount(8);
  await page.getByRole('button', { name: 'בדיקת מקור תמונה 1', exact: true }).click(); await expect(page.getByRole('img', { name: 'מקור תמונת המדף לבדיקה', exact: true })).toBeVisible(); await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'הגדרות', exact: true }).click(); const downloading = page.waitForEvent('download'); await page.getByRole('button', { name: 'הורדת גיבוי הספרייה', exact: true }).click(); const bytes = await readFile((await (await downloading).path())!); const backup = JSON.parse(bytes.toString()); expect(backup.formatVersion).toBe(8); expect(backup.manifestCounts).toMatchObject({ books: 0, copies: 0, recognitionDrafts: 1, images: 2 }); expect(bytes.toString()).not.toContain(key); const itemIds = backup.tables.recognitionDrafts[0].items.map((row: { id: string }) => row.id);
  await page.reload(); await page.getByRole('link', { name: 'כל הספרים', exact: true }).click(); await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click(); await page.getByRole('button', { name: 'צילום מדף בכמה תמונות', exact: true }).click(); await chooseDraft(page); await expect(page.getByText('2 תמונות · 4 פריטים בטיוטה', { exact: true })).toBeVisible(); await expect(page.getByText('מפתח אישי מוגדר בדפדפן הזה.', { exact: true })).toHaveCount(1); expect(calls).toBe(2);
  const storedIds = await page.evaluate(async () => { const modulePath = '/library/src/data/database.ts'; const { db } = await import(modulePath); return (await db.recognitionDrafts.toArray())[0].items.map((row: { id: string }) => row.id); }); expect(storedIds).toEqual(itemIds);
  await page.getByRole('button', { name: 'מחיקת מקור תמונה 1', exact: true }).click(); await expect(page.getByText('מקור התמונה נמחק; תוצאות הזיהוי נשארו בטיוטה.', { exact: true })).toBeVisible(); await expect(page.getByText('2 תמונות · 4 פריטים בטיוטה', { exact: true })).toBeVisible(); expect(errors).toEqual([]);
});
test('T18 refresh asks for original unretained file, never replays recognized images, and keeps quota draft', async ({ page }) => {
  let calls = 0; await page.route('https://generativelanguage.googleapis.com/**', async route => { calls++; await route.fulfill({ status: calls === 1 ? 200 : 429, json: calls === 1 ? payload() : { error: key } }); });
  await open(page); await newDraft(page, false); await page.reload(); await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click(); await page.getByRole('button', { name: 'צילום מדף בכמה תמונות', exact: true }).click(); await chooseDraft(page); await configure(page); await page.getByRole('button', { name: 'התחלת או חידוש התור', exact: true }).click(); await expect(page.getByText('בחר שוב את התמונה כדי להמשיך; המקור לא נשמר.', { exact: true })).toBeVisible(); expect(calls).toBe(0);
  const image = await fixture(page); await page.getByLabel('בחירת אותה תמונה מחדש 1', { exact: true }).setInputFiles(image); await page.getByLabel('בחירת אותה תמונה מחדש 2', { exact: true }).setInputFiles(image); await page.getByRole('button', { name: 'התחלת או חידוש התור', exact: true }).click();
  await expect(page.getByText('המכסה הסתיימה. הטיוטה נשמרה; אין תשלום, חידוש או ניסיון נוסף.', { exact: true })).toBeVisible(); expect(calls).toBe(2); await expect(page.getByText('2 תמונות · 1 פריטים בטיוטה', { exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'התחלת או חידוש התור', exact: true })).toBeDisabled(); await page.keyboard.press('Escape'); await page.reload(); await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click(); await page.getByRole('button', { name: 'צילום מדף בכמה תמונות', exact: true }).click(); await chooseDraft(page); await expect(page.getByText('2 תמונות · 1 פריטים בטיוטה', { exact: true })).toBeVisible(); expect(calls).toBe(2); await page.getByLabel('בחירת אותה תמונה מחדש 1', { exact: true }).setInputFiles(image); await expect(page.getByText('התמונה הותאמה לתצוגת המקור; אין שליחה נוספת.', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'בדיקת מקור תמונה 1', exact: true }).click(); await expect(page.getByRole('img', { name: 'מקור תמונת המדף לבדיקה', exact: true })).toBeVisible(); expect(calls).toBe(2);
});
test('T18 pause releases a pending request, ignores late output, and displays one scrollable list at 360px', async ({ page }) => {
  let calls = 0, release!: () => void; const gate = new Promise<void>(resolve => { release = resolve; });
  await page.route('https://generativelanguage.googleapis.com/**', async route => { calls++; await gate; await route.fulfill({ json: payload() }).catch(() => {}); });
  await open(page); await newDraft(page, true, 1); await configure(page); await page.getByRole('button', { name: 'התחלת או חידוש התור', exact: true }).click(); await expect.poll(() => calls).toBe(1); await page.getByRole('button', { name: 'השהיית התור', exact: true }).click(); release();
  await expect(page.getByText('בקשה שנקטעה', { exact: false })).toBeVisible(); await expect(page.getByText('1 תמונות · 0 פריטים בטיוטה', { exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'אישור ניסיון נוסף לתמונה 1', exact: true })).toBeEnabled();
  await page.setViewportSize({ width: 360, height: 800 }); await page.getByRole('heading', { name: 'תור תמונות', exact: true }).scrollIntoViewIfNeeded(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: 'test-results/phase11-360-queue.png', fullPage: true }); expect(calls).toBe(1);
});
