import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';

async function addBook(page: Page, title: string) {
  await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click();
  await page.getByLabel('שם הספר', { exact: true }).fill(title);
  await page.getByRole('button', { name: 'שמירת הספר', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
}
test('optional book, multiple authors, three copies, editing, archive, narrow layout and keyboard focus', async ({ page }) => {
  await page.goto(''); await addBook(page, '');
  await expect(page.getByRole('heading', { name: 'ללא שם', exact: true })).toBeVisible();
  await page.getByRole('button', { name: /ללא שם.*1 עותקים/ }).click();
  await page.getByLabel('שם הספר', { exact: true }).fill('בדיקת שלב ארבע');
  await page.getByRole('button', { name: 'הוספת מחבר', exact: true }).click();
  await page.getByLabel('שם מחבר 1', { exact: true }).fill('שם עט מלא');
  await page.getByRole('button', { name: 'הוספת מחבר', exact: true }).click();
  await page.getByLabel('שם מחבר 2', { exact: true }).fill('מחבר נוסף');
  await page.getByRole('button', { name: 'שמירת הספר', exact: true }).click();
  await page.getByRole('button', { name: /בדיקת שלב ארבע.*1 עותקים/ }).click();
  await page.getByRole('button', { name: 'הוספת עותק', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'עותקים (2)', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'הוספת עותק', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'עותקים (3)', exact: true })).toBeVisible();
  const card = page.locator('.copy-card').first();
  await card.getByLabel('תיאור העותק').fill('עותק בדיקה'); await card.getByLabel('מחיר בש״ח').fill('19.50');
  await card.getByRole('button', { name: 'שמירת העותק' }).click();
  await expect(page.locator('.copy-card').first().getByLabel('תיאור העותק')).toHaveValue('עותק בדיקה');
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel('שם הספר', { exact: true }).focus(); await page.keyboard.press('Shift+Tab');
  expect(await page.evaluate(() => !!document.activeElement?.closest('dialog'))).toBe(true);
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: 'ארכוב העותק', exact: true }).first().click();
  await expect(page.getByText('עותק בארכיון', { exact: true })).toHaveCount(3);
  await page.getByRole('button', { name: 'סגירה', exact: true }).click();
  await expect(page.locator('.book-list li')).toHaveCount(0);
  await page.getByLabel('כולל ספרים בארכיון').check();
  await expect(page.locator('.book-list li')).toHaveCount(1);
  await page.getByRole('button', { name: /בדיקת שלב ארבע.*0 עותקים/ }).click();
  await page.getByRole('button', { name: 'החזרת העותק מהארכיון' }).first().click();
  await page.getByRole('button', { name: 'סגירה', exact: true }).click(); await page.reload();
  await expect(page.getByText('שם עט מלא · מחבר נוסף')).toBeVisible();
  await expect(page.getByText('1 עותקים')).toBeVisible();
  await page.getByRole('button', { name: 'תצוגה מורחבת' }).click(); await page.reload();
  await expect(page.getByRole('button', { name: 'תצוגה מצומצמת' })).toBeVisible();
});
test('ISBN duplicate decision, unsaved dismissal and stale window edit are safe', async ({ page, context }) => {
  await page.goto(''); await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click();
  await page.getByLabel('שם הספר', { exact: true }).fill('ספר ISBN');
  await page.getByText('פרטים נוספים', { exact: true }).click(); await page.getByLabel('ISBN', { exact: true }).fill('9780306406157');
  await page.getByRole('button', { name: 'שמירת הספר', exact: true }).click();
  await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click();
  await page.getByText('פרטים נוספים', { exact: true }).click(); await page.getByLabel('ISBN', { exact: true }).fill('0306406152');
  await page.getByRole('button', { name: 'שמירת הספר', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'ISBN זה כבר נמצא בספרייה' })).toBeVisible();
  await page.getByRole('button', { name: 'הוספת עותק לספר הקיים' }).click(); await expect(page.getByText('2 עותקים')).toBeVisible();
  await expect(page.locator('.book-list li')).toHaveCount(1);
  await page.getByRole('button', { name: /ספר ISBN.*2 עותקים/ }).click();
  await page.getByLabel('שם הספר', { exact: true }).fill('לא יישמר'); await page.keyboard.press('Escape');
  await expect(page.getByText('יש שינויים שלא נשמרו. לסגור ולוותר עליהם?')).toBeVisible();
  await page.getByRole('button', { name: 'חזרה לעריכה' }).click();
  const other = await context.newPage(); await other.goto(''); await other.getByRole('button', { name: /ספר ISBN.*2 עותקים/ }).click();
  await other.getByLabel('שם הספר', { exact: true }).fill('נשמר בחלון אחר'); await other.getByRole('button', { name: 'שמירת הספר', exact: true }).click();
  await page.getByRole('button', { name: 'שמירת הספר', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'השתנה בחלון אחר' })).toBeVisible();
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'ויתור על השינויים' }).click();
  await expect(page.getByRole('heading', { name: 'נשמר בחלון אחר', exact: true })).toBeVisible();
});
test('real canvas image compression, validation, URL cleanup and safe backup restore round trip', async ({ page }) => {
  await page.addInitScript(() => {
    const active = new Set<string>(); const originalCreate = URL.createObjectURL.bind(URL), originalRevoke = URL.revokeObjectURL.bind(URL);
    URL.createObjectURL = blob => { const url = originalCreate(blob); active.add(url); return url; };
    URL.revokeObjectURL = url => { active.delete(url); originalRevoke(url); };
    Object.defineProperty(window, 'syntheticURLCount', { get: () => active.size });
  });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(''); await page.getByRole('button', { name: 'הוספת ספר', exact: true }).click();
  await page.getByLabel('שם הספר', { exact: true }).fill('ספר עם תמונה');
  await page.getByLabel('תמונת כריכה').setInputFiles({ name: 'not-a-photo.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('synthetic invalid photo') });
  await expect(page.getByRole('alert').filter({ hasText: 'תמונת JPEG' })).toBeVisible();
  await page.getByLabel('תמונת כריכה').setInputFiles({ name: 'fake.heic', mimeType: 'image/heic', buffer: Buffer.from('<svg>synthetic</svg>') });
  await expect(page.getByRole('alert').filter({ hasText: 'HEIC אינו תקין' })).toBeVisible();
  const bytes = await page.evaluate(async () => {
    const canvas = document.createElement('canvas'); canvas.width = 2400; canvas.height = 1600;
    const context = canvas.getContext('2d')!; context.fillStyle = '#1f4d57'; context.fillRect(0, 0, 2400, 1600); context.fillStyle = '#e0834a'; context.fillRect(200, 200, 800, 1000);
    const blob = await new Promise<Blob>(resolve => canvas.toBlob(blob => resolve(blob!), 'image/png'));
    return Array.from(new Uint8Array(await blob.arrayBuffer()));
  });
  await page.getByLabel('תמונת כריכה').setInputFiles({ name: 'synthetic-cover.png', mimeType: 'image/png', buffer: Buffer.from(bytes) });
  await expect(page.getByRole('img', { name: 'כריכת הספר' })).toBeVisible();
  await page.getByRole('button', { name: 'שמירת הספר', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  const imageCheck = await page.evaluate(async () => {
    const path = '/library/src/data/database.ts'; const { db } = await import(/* @vite-ignore */ path); const image = (await db.images.toArray())[0];
    return { width: image.width, height: image.height, bytes: image.byteLength, mime: image.mimeType, sha: image.sha256.length };
  });
  expect(imageCheck).toMatchObject({ width: 1200, height: 800, mime: 'image/jpeg', sha: 64 }); expect(imageCheck.bytes).toBeLessThanOrEqual(1024 * 1024);
  await page.getByRole('link', { name: 'הגדרות', exact: true }).click();
  await expect.poll(() => page.evaluate(() => Reflect.get(window, 'syntheticURLCount'))).toBe(0);
  const downloadEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'הורדת גיבוי הספרייה', exact: true }).click();
  const backup = await readFile(await (await downloadEvent).path());
  await page.getByRole('link', { name: 'כל הספרים', exact: true }).click(); await addBook(page, 'זמני לא לשחזור');
  await page.getByRole('link', { name: 'הגדרות', exact: true }).click();
  await page.getByLabel('בחירת גיבוי לשחזור').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: backup });
  await expect(page.getByRole('heading', { name: 'תצוגה מקדימה: הספרייה שלי' })).toBeVisible();
  await page.getByRole('button', { name: 'ביטול השחזור' }).click();
  await page.getByRole('link', { name: 'כל הספרים', exact: true }).click(); await expect(page.locator('.book-list li')).toHaveCount(2);
  await page.getByRole('link', { name: 'הגדרות', exact: true }).click();
  await page.getByLabel('בחירת גיבוי לשחזור').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: backup });
  await expect(page.getByRole('heading', { name: /תצוגה מקדימה/ })).toBeVisible();
  const safetyEvent = page.waitForEvent('download'); await page.getByRole('button', { name: 'הורדת גיבוי מגן לפני החלפה' }).click(); await safetyEvent;
  await expect(page.getByRole('button', { name: 'החלפת הספרייה ושחזור' })).toBeDisabled();
  await page.getByLabel('וידאתי שהגיבוי ירד למחשב ואני מאשר החלפה').check(); await page.getByRole('button', { name: 'החלפת הספרייה ושחזור' }).click();
  await expect(page.getByText('הספרייה שוחזרה בהצלחה.')).toBeVisible();
  await page.getByRole('link', { name: 'כל הספרים', exact: true }).click(); await page.reload();
  await expect(page.locator('.book-list li')).toHaveCount(1); await expect(page.getByRole('img', { name: 'כריכת הספר' })).toBeVisible();
  const corruptCheck = await page.evaluate(async () => {
    const path = '/library/src/data/backup.ts', hashPath = '/library/src/data/images.ts';
    const { createSnapshot, validateBackup } = await import(/* @vite-ignore */ path); const { hashBytes } = await import(/* @vite-ignore */ hashPath);
    const dbPath = '/library/src/data/database.ts'; const { db } = await import(/* @vite-ignore */ dbPath);
    const backup = JSON.parse((await createSnapshot(db)).text); backup.data.images[0].width = 999;
    backup.checksum = await hashBytes(new TextEncoder().encode(JSON.stringify(backup.data)).buffer);
    try { await validateBackup(JSON.stringify(backup)); return false; } catch { return true; }
  });
  expect(corruptCheck).toBe(true); expect(errors).toEqual([]);
});
test('deletion needs preview, protective download and explicit confirmation', async ({ page }) => {
  await page.goto(''); await addBook(page, 'מחיקת בדיקה'); await page.getByRole('button', { name: /מחיקת בדיקה.*1 עותקים/ }).click();
  await page.getByText('מחיקת הספר', { exact: true }).click();
  await expect(page.getByText(/יימחקו הספר, 1 העותקים/)).toBeVisible();
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'הורדת גיבוי מגן לפני מחיקה' }).click(); await download;
  await expect(page.getByRole('button', { name: 'מחיקה סופית של הספר' })).toBeDisabled();
  await page.getByLabel('וידאתי שהגיבוי ירד למחשב ואני מאשר את המחיקה').check();
  await page.getByRole('button', { name: 'מחיקה סופית של הספר' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.book-list li')).toHaveCount(0);
});
