import { useState } from 'react';
import { forgetGoodreadsKey, goodreadsConfigured, rememberGoodreadsKey } from './data/goodreads';
import { errorMessage } from './data/errors';
export default function GoodreadsKey() {
  const [ready, setReady] = useState(goodreadsConfigured), [value, setValue] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [warning, setWarning] = useState(false);
  return <section data-update-blocked={busy || !!value}><p className="hint">שירות הקטלוג הפרטי בשרת שלך מחבר את דני ספרים, הספרייה הלאומית ו־Goodreads. מפתח הספרייה הלאומית נשמר רק בשרת ואינו נדרש במכשיר. זהו חיבור לשירות שלנו, ולא ל־API של Goodreads. הזן את מפתח שירות הקטלוג שקיבלת בעת ההתקנה. חיפוש לפי שם ב־Goodreads עלול להיחסם; חיפוש ISBN עשוי להישאר זמין. המפתח נשמר במכשיר בנפרד מהספרים והגיבויים.</p>
    {ready ? <><p>שירות הקטלוג הפרטי מוגדר במכשיר הזה.</p><button type="button" className="secondary" disabled={busy} onClick={async () => { setBusy(true); setWarning(false); try { await forgetGoodreadsKey(); setReady(false); setMessage('מפתח הגישה נמחק מהמכשיר.'); } catch (error) { setWarning(true); setMessage(errorMessage(error)); } finally { setBusy(false); } }}>מחיקת מפתח שירות הקטלוג</button></> : <form onSubmit={async event => { event.preventDefault(); setBusy(true); setWarning(false); try { await rememberGoodreadsKey(value); setReady(true); setValue(''); setMessage('מפתח הגישה נשמר. החיבור ייבדק בחיפוש הבא.'); } catch (error) { setWarning(true); setReady(goodreadsConfigured()); setValue(''); setMessage(errorMessage(error)); } finally { setBusy(false); } }}><label className="field">מפתח שירות הקטלוג הפרטי<input type="password" autoComplete="off" spellCheck={false} autoCapitalize="none" dir="ltr" maxLength={64} value={value} onChange={event => setValue(event.target.value)} /></label><button type="submit" disabled={busy || !value.trim()}>שמירת מפתח שירות הקטלוג</button></form>}
    {message && <p role={warning ? "alert" : "status"}>{message}</p>}
  </section>;
}
