import type { Book, Copy, Loan, NamedItem, Shelf } from './data/models';
export function UserStatistics({ books, copies, loans, genres, shelves }: { books: Book[]; copies: Copy[]; loans: Loan[]; genres: NamedItem[]; shelves: Shelf[] }) {
  const ratings = books.flatMap(book => book.rating ? [book.rating] : []);
  const active = copies.filter(copy => !copy.archivedAt), borrowed = new Set(loans.filter(loan => !loan.returnedAt).map(loan => loan.copyId));
  const spending = new Map<string, number>();
  for (const copy of copies) if (copy.purchasePriceMinor !== null && copy.currency) spending.set(copy.currency, (spending.get(copy.currency) ?? 0) + copy.purchasePriceMinor / 100);
  const money = new Intl.NumberFormat('he-IL', { style: 'currency', currency: 'ILS' });
  return <section aria-label="סטטיסטיקות הספרייה"><dl className="user-statistics"><div><dt>ספרים</dt><dd>{books.length}</dd></div><div><dt>מדפים</dt><dd>{shelves.length}</dd></div><div><dt>סך הוצאה כספית</dt><dd>{money.format(spending.get('ILS') ?? 0)}{[...spending].filter(([currency]) => currency !== 'ILS').map(([currency, amount]) => <small key={currency}>{new Intl.NumberFormat('he-IL', { style: 'currency', currency }).format(amount)}</small>)}</dd></div><div><dt>עותקים פעילים</dt><dd>{active.length}</dd></div><div><dt>עותקים מושאלים</dt><dd>{active.filter(copy => borrowed.has(copy.id)).length}</dd></div><div><dt>דירוג ממוצע</dt><dd>{ratings.length ? (ratings.reduce((sum, rating) => sum + rating, 0) / ratings.length).toFixed(1) + '/5' : 'טרם דורגו ספרים'}</dd></div><div><dt>ספרים מדורגים</dt><dd>{ratings.length}</dd></div></dl><h3>ספרים לפי ז׳אנר</h3><ul>{genres.map(genre => <li key={genre.id}>{genre.name}: {books.filter(book => book.genreIds.includes(genre.id)).length}</li>)}<li>ללא ז׳אנר: {books.filter(book => !book.genreIds.length).length}</li></ul></section>;
}
