import { useState } from 'react';
import { geminiVisionSession, personalVisionSession } from './data/vision';
import { forgetVisionKey, rememberVisionKey } from './data/visionCredentials';
import { errorMessage } from './data/errors';

export default function VisionKey({ onChange }: { onChange?: (ready: boolean) => void }) {
  const [key, setKey] = useState(''), [free, setFree] = useState(false), [consent, setConsent] = useState(false), [ready, setReady] = useState(geminiVisionSession.ready), [message, setMessage] = useState('');
  const [saving, setSaving] = useState(false);
  async function forget() { setSaving(true); geminiVisionSession.clear(); setReady(false); onChange?.(personalVisionSession.ready); try { await forgetVisionKey(); setKey(''); setFree(false); setConsent(false); setMessage('המפתח נמחק מהמכשיר.'); } catch { setMessage('הזיהוי נעצר, אך מחיקת המפתח השמור לא הושלמה. נסה שוב לפני סגירת החלון.'); } finally { setSaving(false); } }
  return <section className="vision-key" data-update-blocked={saving || !!key || (!ready && (free || consent))}><h3>מפתח אישי לזיהוי תמונה</h3><p className="hint">מגדירים פעם אחת: המפתח נשמר בדפדפן הזה ונטען בפתיחה מחדש. הוא אינו נכלל בגיבוי או ב־Excel. מי שיש לו גישה לדפדפן הזה יכול להשתמש בו; אפשר למחוק אותו כאן. התמונה המוכנה תישלח ל־Google Gemini; לא נשלחים הספרייה או ההערות שלך. במסלול החינמי Google עשויה להשתמש בתוכן לשיפור מוצריה.</p><p className="hint">אין תשלום, טעינה או חידוש. בדוק ב־<a href="https://aistudio.google.com/api-keys" target="_blank" rel="noopener noreferrer">Google AI Studio</a> שהפרויקט של המפתח מסומן Free ושאין בו חיוב פעיל. אם המצב אינו ברור, השאר את הזיהוי חסום.</p>
    {ready && geminiVisionSession.ready ? <div className="actions"><p role="status">מפתח אישי מוגדר בדפדפן הזה.</p><button type="button" className="secondary" disabled={saving} onClick={() => void forget()}>מחיקת המפתח מהמכשיר</button></div> : <form onSubmit={async event => { event.preventDefault(); setSaving(true); try { geminiVisionSession.configure(key.trim(), free, consent); const enabled = geminiVisionSession.ready; setKey(''); setReady(enabled); if (enabled) { try { await rememberVisionKey(key.trim(), free, consent); setMessage('המפתח נשמר בדפדפן הזה. אין צורך להכניס אותו שוב בפתיחה מחדש.'); } catch { setMessage('המפתח זמין לביקור הזה, אך לא נשמר בדפדפן. יהיה צורך להכניס אותו שוב.'); } } else setMessage('השליחה נשארה חסומה.'); onChange?.(personalVisionSession.ready); } catch (error) { setMessage(errorMessage(error)); } finally { setSaving(false); } }}>
      <label className="field">מפתח Gemini אישי<input type="password" autoComplete="off" autoCapitalize="none" spellCheck={false} dir="ltr" maxLength={4096} value={key} onChange={event => setKey(event.target.value)} /></label><p className="hint">שמירת המפתח אינה בדיקת חיבור ל־Google. המפתח נבדק בשירות רק כששולחים תמונה לזיהוי.</p>
      <label className="check"><input type="checkbox" checked={free} onChange={event => setFree(event.target.checked)} />בדקתי שהפרויקט של המפתח הוא Free, ללא חיוב פעיל</label><label className="check"><input type="checkbox" checked={consent} onChange={event => setConsent(event.target.checked)} />אני מסכים לשליחת התמונה המוכנה ל־Google Gemini</label><button type="submit" disabled={saving || !key.trim() || !free || !consent}>שמירת מפתח Gemini</button>
    </form>}{geminiVisionSession.hasKey && !(ready && geminiVisionSession.ready) && <button type="button" className="secondary" disabled={saving} onClick={() => void forget()}>מחיקת המפתח מהמכשיר</button>}{message && <p role="status" className="form-status">{message}</p>}
  </section>;
}
